apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-node-app
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Pratibha2411/hello-node.git
    path: hello-node-chart
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

